# Site settings
title: Sapan's Blog
email: sapanagrawal777@gmail.com
description: "My Personal Blog"
baseurl: ""
url: "https://cs231n.github.io"
courseurl: "https://sapan-ostic.github.io/"
twitter_username: cs231n
github_username: sapan-ostic

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# links to homeworks
hw_1_colab: https://cs231n.github.io/assignments/2022/assignment1_colab.zip
hw_2_colab: https://cs231n.github.io/assignments/2022/assignment2_colab.zip
hw_3_colab: https://cs231n.github.io/assignments/2022/assignment3_colab.zip
